---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: cluster-admin-custom
  rules:
  - apiGroups:
    - '*'
    attributeRestrictions: null
    resources:
    - '*'
    verbs:
    - '*'
  - apiGroups: null
    attributeRestrictions: null
    nonResourceURLs:
    - '*'
    resources: []
    verbs:
    - '*'
- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    name: cluster-admin-custom
  roleRef:
    name: cluster-admin-custom
  subjects:
  - kind: User
    name: user1
  - kind: User
    name: user2
  userNames:
  - user1
  - user2
